name: Election Predictor CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

#TODO ensure Slack integration is notifying on failure
jobs:
  build-and-run-pytest:

    runs-on: ubuntu-latest

    steps:
    # First step (unnamed here) is to checkout to the branch that triggered the event
    - uses: actions/checkout@v3

    # Second step: install python 3.10.6
    - name: Set up Python 3.10.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.6"

# Third step: install python packages using a requirements file
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip cython wheel
        pip install -r requirements.txt

    # Fourth step: run tests with Pytest
    - name: Run tests
      run: make

# Fourth step: format code with Black
  - name: Format with Black
    run: black .
    

#TODO Add containerisation step to build Docker image

#TODO Add deployment step to deploy to Cloud Run
